# Generated by Django 4.2.4 on 2023-09-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='date',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='location',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='time',
        ),
        migrations.AddField(
            model_name='charge',
            name='image',
            field=models.ImageField(null=True, upload_to='vehicle_images'),
        ),
    ]
