# Generated by Django 4.2.4 on 2023-09-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_charge_category_remove_charge_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('vehicle_category', models.IntegerField(default=True)),
                ('Type_of_service', models.CharField(max_length=100, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='vehicle_images')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='station_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='vehicle_category',
            field=models.IntegerField(default=True),
        ),
    ]
